name: Playwright Setup
description: Set up Playwright (for Linux)

runs:
  using: composite
  steps:
    - name: Get Playwright version
      id: playwright-version
      run: echo "playwright-version=$(npm ll -p -a playwright | sed 's/^.*@//')" >> ${GITHUB_OUTPUT}
      shell: bash

    - name: Cache Playwright binaries
      id: playwright-cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.playwright-version }}
        restore-keys: ${{ runner.os }}-playwright-

    - name: Install Playwright
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      run: npx playwright install --with-deps
      shell: bash
