name: Deployment
description: Deploy to preview or production environment

inputs:
  environment:
    description: "Environment to deploy to. (preview | production)"
    required: true

runs:
  using: composite
  steps:
    - name: Set environment flag
      shell: bash
      run: |
        if [ ${{ inputs.environment }} = "production" ]; then
          echo "ENV_FLAG=--prod" >> $GITHUB_ENV
        fi

    - name: Install Vercel CLI
      shell: bash
      run: npm i -g vercel

    - name: Pull environment information
      shell: bash
      run: vercel pull --yes --environment=${{ inputs.environment }} --token=$VERCEL_TOKEN

    - name: Build
      shell: bash
      run: vercel build $ENV_FLAG --token=$VERCEL_TOKEN

    - name: Deploy
      shell: bash
      run: vercel deploy --prebuilt $ENV_FLAG --token=$VERCEL_TOKEN > deployment_url.txt
    
    - name: Create GitHub Deployment
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        ENVIRONMENT=${{ inputs.environment }}
        DEPLOYMENT_ID=$(gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          repos/${{ github.repository }}/deployments \
          -F ref=${{ github.sha }} \
          -F environment=${ENVIRONMENT^} \
          -F auto_merge=false \
          -F required_contexts[]=check \
          -F required_contexts[]=test \
          -q ".id")
        gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ github.repository }}/deployments/$DEPLOYMENT_ID/statuses \
          -F state=success \
          -F environment_url=$(cat deployment_url.txt) \
          -F log_url=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
